name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-web-app:latest1 .

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag my-web-app:latest ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest
